# traefik + nginx + php-fpm + mysql + phpmyadmin + portainer
version: '3.4'
services:
    traefik:
        container_name: REPLACE_DOMAIN_NAME_traefik
        image: traefik:1.7.28-alpine
        ports:
            - "HTTP_PORT:80"
            #- "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik/traefik.toml:/etc/traefik/traefik.toml
            - ./traefik/acme:/etc/traefik/acme
        labels:
            - traefik.backend=traefik
            - traefik.frontend.rule=Host:www.traefik.REPLACE_DOMAIN_NAME,traefik.REPLACE_DOMAIN_NAME
            - traefik.port=8080
        networks:
            - proxy.REPLACE_DOMAIN_NAME
            
    nginx:
        container_name: REPLACE_DOMAIN_NAME_nginx
        image: nginx:latest
        volumes:
            - ../:/var/www
            - /var/www/docker
            - /var/www/mysql
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/logs:/var/log/nginx
        labels:
            - traefik.backend=nginx
            - traefik.frontend.rule=Host:www.REPLACE_DOMAIN_NAME,REPLACE_DOMAIN_NAME
            - traefik.port=80
        networks:
            - proxy.REPLACE_DOMAIN_NAME
        links:
            - php-fpm
        depends_on:
            - mysql

    php-fpm:
        container_name: REPLACE_DOMAIN_NAME_php-fpm
        build: ./php-fpm
        expose:
            - "9000"
        volumes:
            - ../:/var/www
            - /var/www/docker
            - /var/www/mysql
            - ./php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        labels:
            - traefik.enable=false
        networks:
            - proxy.REPLACE_DOMAIN_NAME
        links:
            - mysql
        depends_on:
            - mysql

    mysql:
        container_name: REPLACE_DOMAIN_NAME_mysql
        image: mysql:5.7.22
        expose:
            - "3306"
        volumes:
            - mysql/data:/var/lib/mysql
        env_file: ./mysql/config.ini
        labels:
            - traefik.enable=false
        networks:
            - proxy.REPLACE_DOMAIN_NAME

    phpmyadmin:
        container_name: REPLACE_DOMAIN_NAME_phpmyadmin
        image: phpmyadmin/phpmyadmin
        labels:
            - traefik.backend=pma
            - traefik.frontend.rule=Host:www.pma.REPLACE_DOMAIN_NAME,pma.REPLACE_DOMAIN_NAME
            - traefik.port=80
        environment:
            PMA_HOST: mysql
        networks:
             - proxy.REPLACE_DOMAIN_NAME
        links:
            - mysql
        depends_on:
            - mysql
            
    portainer:
        container_name: REPLACE_DOMAIN_NAME_portainer
        image: portainer/portainer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./portainer:/data
        labels:
            - traefik.backend=portainer
            - traefik.frontend.rule=Host:www.portainer.REPLACE_DOMAIN_NAME,portainer.REPLACE_DOMAIN_NAME
            - traefik.port=9000
        networks:
             - proxy.REPLACE_DOMAIN_NAME

networks:
    proxy.REPLACE_DOMAIN_NAME:        
        driver: overlay
        external: true
