defaultEntryPoints = ["http"]
logLevel="DEBUG"

[entryPoints]
    [entryPoints.http]
        address = ":80"
    [entryPoints.traefik]
        address = ":8080"

[api]
    entryPoint = "traefik"
    dashboard = true

[docker]
    domain = "tera.local"
    watch = true
    exposedByDefault = true
    swarmMode = false