defaultEntryPoints = ["http", "https"]
logLevel="DEBUG"

[entryPoints]
    [entryPoints.http]
        address = ":80"
        [entryPoints.http.redirect]
            entryPoint = "https"
    [entryPoints.https]
        address = ":443"
        [entryPoints.https.redirect]
            regex = "^https://www.(.*)"
            replacement = "https://$1"
        [entryPoints.https.tls]
    [entryPoints.traefik]
        address = ":8080"
        [entryPoints.traefik.auth.basic]
            users = ["admin:$apr1$vngADTJE$ALEsBhnVuvYyyqXWtke3P0"]

[acme]
    email = "localhost"
    storage = "acme.json"
    entryPoint = "https"
    [[acme.domains]]
        main = "tera.local"
        sans = [
            "www.tera.local",
            "www.traefik.tera.local", 
            "www.pma.tera.local", 
            "www.portainer.tera.local",
            "traefik.tera.local", 
            "pma.tera.local", 
            "portainer.tera.local"
        ]
    [acme.httpChallenge]
        entryPoint = "http"

[api]
    entryPoint = "traefik"
    dashboard = true

[docker]
    domain = "tera.local"
    watch = true
    exposedByDefault = true
    swarmMode = false